export const fullInventory = [
    {
        "codigo": "00069890",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-142 MP",
        "marca": "DRAGER",
        "modelo": "PSS7000",
        "serie": "BRAC-1034-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00069891",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-142 MP",
        "marca": "DRAGER",
        "modelo": "PSS 7000",
        "serie": "BRAD-1011-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "70001",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BARD-0193-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070002",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0235-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070003",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRFF-0240",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070166",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRTF-4941-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070167",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRFF-0228-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070168",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0251-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070169",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0242-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070170",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0192-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070171",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0263-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070172",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0226-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070173",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRTF-4963-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070174",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRTF-3934-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070175",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0240-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070176",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRTF-3933-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00070177",
        "sicafi": "",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE AIRE",
        "ubicacion": "I-252-MF",
        "marca": "DRAGER",
        "modelo": "NA",
        "serie": "BRAD-0250-09",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065456",
        "sicafi": "00065456",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303306",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065457",
        "sicafi": "00065457",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303245",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065458",
        "sicafi": "00065458",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303283",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065459",
        "sicafi": "00065459",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303253",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065461",
        "sicafi": "00065461",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303241",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065462",
        "sicafi": "00065462",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303246",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065463",
        "sicafi": "00065463",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303285",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065464",
        "sicafi": "00065464",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-115-ER",
        "marca": "UNCURVE 33651-02",
        "modelo": "A2303250",
        "serie": "",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065465",
        "sicafi": "00065465",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-142 MP",
        "marca": "INTERSPIRO",
        "modelo": "UNCURVE 33651-02",
        "serie": "A2303242",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065466",
        "sicafi": "00065466",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-142 MP",
        "marca": "INTERSPIRO",
        "modelo": "UNCURVE 33651-02",
        "serie": "A2303258",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065467",
        "sicafi": "00065467",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-142 MP",
        "marca": "INTERSPIRO",
        "modelo": "UNCURVE 33651-02",
        "serie": "A2303244",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00065468",
        "sicafi": "00065468",
        "pf": "-",
        "descripcion": "ARNES PARA EQUIPO DE RESPIRACIÓN AUTONOMA MASCARA",
        "ubicacion": "I-142 MP",
        "marca": "INTERSPIRO",
        "modelo": "UNCURVE 33651-02",
        "serie": "A2303319",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026494",
        "sicafi": "1014992",
        "pf": "10282",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37985",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026495",
        "sicafi": "1014993",
        "pf": "10299",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38149",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026496",
        "sicafi": "1014994",
        "pf": "10188",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38766",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026498",
        "sicafi": "1014996",
        "pf": "10293",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38531",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026499",
        "sicafi": "1014997",
        "pf": "10302",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38446",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026501",
        "sicafi": "1014999",
        "pf": "10310",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38559",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026502",
        "sicafi": "1015000",
        "pf": "10169",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38540",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026504",
        "sicafi": "1015002",
        "pf": "10201",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38261",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026505",
        "sicafi": "1015003",
        "pf": "10886",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38575",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026506",
        "sicafi": "1015004",
        "pf": "10296",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38529",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026507",
        "sicafi": "1015005",
        "pf": "10168",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38444",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026508",
        "sicafi": "1015006",
        "pf": "10277",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38167",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026510",
        "sicafi": "1015008",
        "pf": "10179",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38045",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026511",
        "sicafi": "1015009",
        "pf": "10177",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38466",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026512",
        "sicafi": "1015010",
        "pf": "10184",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38012",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026513",
        "sicafi": "1015011",
        "pf": "10175",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38163",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026514",
        "sicafi": "1015012",
        "pf": "10190",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37965",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026516",
        "sicafi": "1015014",
        "pf": "10292",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38425",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026517",
        "sicafi": "1015015",
        "pf": "10309",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38829",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026518",
        "sicafi": "1015016",
        "pf": "10300",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38098",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026519",
        "sicafi": "1015017",
        "pf": "10294",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38667",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026520",
        "sicafi": "1015018",
        "pf": "10197",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38357",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026521",
        "sicafi": "1015019",
        "pf": "10183",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38022",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026522",
        "sicafi": "1015020",
        "pf": "10304",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38749",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026523",
        "sicafi": "1015021",
        "pf": "10303",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38757",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026525",
        "sicafi": "1015023",
        "pf": "10171",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37930",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026526",
        "sicafi": "1015024",
        "pf": "10186",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38279",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026527",
        "sicafi": "1015025",
        "pf": "10185",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38129",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026529",
        "sicafi": "1015027",
        "pf": "10198",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38355",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026530",
        "sicafi": "1015028",
        "pf": "10307",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38211",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026531",
        "sicafi": "1015029",
        "pf": "10187",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38631",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026532",
        "sicafi": "1015030",
        "pf": "10181",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38052",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026534",
        "sicafi": "1015032",
        "pf": "10289",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37928",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026535",
        "sicafi": "1015033",
        "pf": "10278",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38623",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026536",
        "sicafi": "1015034",
        "pf": "10291",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38738",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026563",
        "sicafi": "1015068",
        "pf": "10288",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38259",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026564",
        "sicafi": "1015069",
        "pf": "10176",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38267",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026565",
        "sicafi": "1015070",
        "pf": "10193",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38280",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026566",
        "sicafi": "1015071",
        "pf": "10180",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38824",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026567",
        "sicafi": "1015072",
        "pf": "10290",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38765",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026568",
        "sicafi": "1015073",
        "pf": "10283",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38726",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026570",
        "sicafi": "1015075",
        "pf": "10165",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38311",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026571",
        "sicafi": "1015076",
        "pf": "10301",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38107",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026572",
        "sicafi": "1015077",
        "pf": "10195",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38148",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026573",
        "sicafi": "1015078",
        "pf": "10285",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38810",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026574",
        "sicafi": "1015079",
        "pf": "10281",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38822",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026575",
        "sicafi": "1015080",
        "pf": "10182",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38745",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026576",
        "sicafi": "1015081",
        "pf": "10200",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38727",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026577",
        "sicafi": "1015082",
        "pf": "10305",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38761",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026578",
        "sicafi": "1015083",
        "pf": "10189",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38731",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026579",
        "sicafi": "1015084",
        "pf": "10166",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38740",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026580",
        "sicafi": "1015085",
        "pf": "10170",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38136",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026581",
        "sicafi": "1015086",
        "pf": "10286",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38734",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026582",
        "sicafi": "1015087",
        "pf": "10173",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38571",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026583",
        "sicafi": "1015088",
        "pf": "45512",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38376",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026584",
        "sicafi": "1015089",
        "pf": "10280",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38142",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026585",
        "sicafi": "1015090",
        "pf": "10199",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38348",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026586",
        "sicafi": "1015091",
        "pf": "10194",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38735",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026587",
        "sicafi": "1015092",
        "pf": "10287",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38352",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026588",
        "sicafi": "1015093",
        "pf": "10191",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38382",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026589",
        "sicafi": "1015094",
        "pf": "10174",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38736",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026590",
        "sicafi": "1015095",
        "pf": "10306",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38638",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026591",
        "sicafi": "1015096",
        "pf": "10295",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38150",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026592",
        "sicafi": "1015097",
        "pf": "10298",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38374",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026593",
        "sicafi": "1015098",
        "pf": "10167",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38747",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026594",
        "sicafi": "1015099",
        "pf": "10297",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38400",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026595",
        "sicafi": "1015100",
        "pf": "10164",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38389",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026596",
        "sicafi": "1015101",
        "pf": "10279",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38378",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026597",
        "sicafi": "1015102",
        "pf": "10284",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38792",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026599",
        "sicafi": "1015104",
        "pf": "45513",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38424",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026610",
        "sicafi": "1015115",
        "pf": "10308",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-115-ER",
        "marca": "COMPOSITE 6.9",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37996",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026490",
        "sicafi": "1014988",
        "pf": "28830",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-142 MP",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38266",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026491",
        "sicafi": "1014989",
        "pf": "28834",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-142 MP",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37990",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026492",
        "sicafi": "1014990",
        "pf": "28882",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-142 MP",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38361",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026493",
        "sicafi": "1014991",
        "pf": "28884",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-142 MP",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38034",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026487",
        "sicafi": "1014985",
        "pf": "13504",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38128",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026488",
        "sicafi": "1014986",
        "pf": "13505",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38070",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026515",
        "sicafi": "1015013",
        "pf": "10163",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38505",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026524",
        "sicafi": "1015022",
        "pf": "13508",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37992",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026528",
        "sicafi": "1015026",
        "pf": "13507",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-37977",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026603",
        "sicafi": "1015108",
        "pf": "10879",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38353",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026606",
        "sicafi": "1015111",
        "pf": "10887",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38278",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026608",
        "sicafi": "1015113",
        "pf": "10882",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-252-MF",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38656",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026489",
        "sicafi": "1014987",
        "pf": "14668",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38692",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026904",
        "sicafi": "1015550",
        "pf": "13623",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "92.FJM:38538",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026905",
        "sicafi": "1015551",
        "pf": "13689",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "94.FJM:38549",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026906",
        "sicafi": "1015552",
        "pf": "13650",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "94.FJM:38788",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026908",
        "sicafi": "1015554",
        "pf": "13672",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "96.FJM:38162",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026909",
        "sicafi": "1015555",
        "pf": "13695",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "97.FJM:38742",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026910",
        "sicafi": "1015556",
        "pf": "13676",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "98.FJM:38290",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026911",
        "sicafi": "1015557",
        "pf": "13678",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "99.FJM:38512",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026913",
        "sicafi": "1015559",
        "pf": "13653",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "101.FJM:38423",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026914",
        "sicafi": "1015560",
        "pf": "13631",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM-38685",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026917",
        "sicafi": "1015563",
        "pf": "13647",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "106.FJM:38675",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026918",
        "sicafi": "1015564",
        "pf": "13610",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "107.FJM:38506",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026920",
        "sicafi": "1015566",
        "pf": "13630",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "109.FJM:38027",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026921",
        "sicafi": "1015567",
        "pf": "13711",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "110.FJM:38051",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026924",
        "sicafi": "1015570",
        "pf": "13725",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "113.FJM:38633",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026925",
        "sicafi": "1015571",
        "pf": "13701",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "113.FJM:38707",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026926",
        "sicafi": "1015572",
        "pf": "13697",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "114.FJM:38362",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026927",
        "sicafi": "1015573",
        "pf": "13655",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "115.FJM:38743",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026928",
        "sicafi": "1015574",
        "pf": "13661",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "116.FJM:38185",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026929",
        "sicafi": "1015575",
        "pf": "13692",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "117.FJM:38498",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026931",
        "sicafi": "1015577",
        "pf": "13642",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "119.FJM:38604",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026934",
        "sicafi": "1015580",
        "pf": "13634",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38718",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026935",
        "sicafi": "1015581",
        "pf": "13657",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38398",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026936",
        "sicafi": "1015582",
        "pf": "13702",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38112",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026937",
        "sicafi": "1015583",
        "pf": "13663",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38510",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026938",
        "sicafi": "1015584",
        "pf": "13645",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38586",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026939",
        "sicafi": "1015585",
        "pf": "13674",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38326",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026940",
        "sicafi": "1015586",
        "pf": "13607",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38306",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026942",
        "sicafi": "1015588",
        "pf": "13699",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38216",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026943",
        "sicafi": "1015589",
        "pf": "13619",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38160",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026944",
        "sicafi": "1015590",
        "pf": "13669",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38035",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026946",
        "sicafi": "1015592",
        "pf": "13654",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38309",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026947",
        "sicafi": "1015593",
        "pf": "13691",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38746",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026949",
        "sicafi": "1015595",
        "pf": "13698",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38206",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026950",
        "sicafi": "1015596",
        "pf": "13652",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38281",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026951",
        "sicafi": "1015597",
        "pf": "13646",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38821",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026952",
        "sicafi": "1015598",
        "pf": "13660",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38260",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026953",
        "sicafi": "1015599",
        "pf": "13667",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38669",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026955",
        "sicafi": "1015601",
        "pf": "13638",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38066",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026957",
        "sicafi": "1015603",
        "pf": "13719",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38056",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026958",
        "sicafi": "1015604",
        "pf": "13664",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38213",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026959",
        "sicafi": "1015605",
        "pf": "13614",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38082",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026960",
        "sicafi": "1015606",
        "pf": "13633",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38210",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026962",
        "sicafi": "1015608",
        "pf": "13685",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38044",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026963",
        "sicafi": "1015609",
        "pf": "13717",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38076",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026964",
        "sicafi": "1015610",
        "pf": "13643",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38812",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026965",
        "sicafi": "1015611",
        "pf": "13629",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38057",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026966",
        "sicafi": "1015612",
        "pf": "13618",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38173",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026969",
        "sicafi": "1015615",
        "pf": "13658",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38053",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026970",
        "sicafi": "1015616",
        "pf": "13620",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38331",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026972",
        "sicafi": "1015618",
        "pf": "13668",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38196",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026974",
        "sicafi": "1015620",
        "pf": "13722",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38427",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026975",
        "sicafi": "1015621",
        "pf": "13712",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38060",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026976",
        "sicafi": "1015622",
        "pf": "45924",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38195",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026977",
        "sicafi": "1015623",
        "pf": "13671",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38218",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026979",
        "sicafi": "1015625",
        "pf": "13616",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38673",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026987",
        "sicafi": "1015633",
        "pf": "13626",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM37988",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026988",
        "sicafi": "1015634",
        "pf": "13723",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38708",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026991",
        "sicafi": "1015637",
        "pf": "13713",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38101",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026992",
        "sicafi": "1015638",
        "pf": "13690",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38296",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026993",
        "sicafi": "1015639",
        "pf": "13648",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38336",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026994",
        "sicafi": "1015640",
        "pf": "13617",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38791",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026995",
        "sicafi": "1015641",
        "pf": "13677",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38075",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026997",
        "sicafi": "1015643",
        "pf": "13622",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38557",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00026999",
        "sicafi": "1015645",
        "pf": "13651",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38324",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027000",
        "sicafi": "1015646",
        "pf": "13707",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38345",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027001",
        "sicafi": "1015647",
        "pf": "13662",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38307",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027003",
        "sicafi": "1015649",
        "pf": "13682",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38312",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027004",
        "sicafi": "1015650",
        "pf": "13628",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38386",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027005",
        "sicafi": "1015651",
        "pf": "13636",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38065",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027006",
        "sicafi": "1015652",
        "pf": "13703",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38332",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027008",
        "sicafi": "1015654",
        "pf": "13641",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38221",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027010",
        "sicafi": "1015656",
        "pf": "13688",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38610",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027011",
        "sicafi": "1015657",
        "pf": "13649",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38599",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027012",
        "sicafi": "1015658",
        "pf": "13693",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38491",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027013",
        "sicafi": "1015659",
        "pf": "13624",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38062",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027015",
        "sicafi": "1015661",
        "pf": "13621",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38601",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027016",
        "sicafi": "1015662",
        "pf": "13665",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38561",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027017",
        "sicafi": "1015663",
        "pf": "13694",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38072",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027020",
        "sicafi": "1015666",
        "pf": "13666",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38526",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00027021",
        "sicafi": "1015667",
        "pf": "13625",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-358-ER",
        "marca": "AIRBOX",
        "modelo": "NA",
        "serie": "FJM38080",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    },
    {
        "codigo": "00025465",
        "sicafi": "1013970",
        "pf": "45929",
        "descripcion": "CILINDRO / EQ. RESP. AUTON. + VALVULA",
        "ubicacion": "I-496 T-7",
        "marca": "AIRBOX",
        "modelo": "COMPOSITE 6.9",
        "serie": "FJM-38291",
        "estado": "bueno",
        "revisado": false,
        "comentarios": "",
        "fotoUrl": ""
    }
];
